### PR TITLE
Updates from forks

### PR DESCRIPTION
**Pull request by tombruijn**
This PR updates this Mongoid fork of the mongo_session_store gem. These include updates from the last 6 years from the [ryanfitz/mongo_session_store](https://github.com/ryanfitz/mongo_session_store), [brianhempel/mongo_session_store](https://github.com/brianhempel/mongo_session_store) and [appsignal/mongo_session_store](https://github.com/appsignal/mongo_session_store) forks.

Related issue: https://github.com/brianhempel/mongo_session_store/issues/34

## Changes

- Rails 3 support dropped
- Rails 4 support added
- MongoMapper support dropped
- Mongo Ruby driver support added
- Custom session class support added (needs documentation)
- Updated Mongoid version
- Updated to work against a modern Rack version
- Allow custom collections for sessions
- Moved serialization logic to session "models" rather than their parent class so queried models can deserialize session data themselves.
- Expanded test suite
- Test against MongoDB 3
- TravisCI builds for Rails 4.0, 4.1 and 4.2 versions
- Rubocop validation

## Things to discuss

- Rails 3 support -- add official support back? -- I dropped support since there's the [mongo_session_store-rails3](https://rubygems.org/gems/mongo_session_store-rails3) gem
- jRuby & Rubinius support -- add support back? was added by Brian Hempel in his fork -- doesn't have to be this PR.
- MongoMapper support -- add official support back? -- doesn't have to be this PR.
- "Ownership" in terms of who is named in the gemspec after all these forks and updates. I've deliberately left it alone in this PR after the changes in my fork.

## Next steps

- Rails 5 support, see [drgcms](https://github.com/brianhempel/mongo_session_store/compare/master...drgcms:rails5)'s fork for a start.
- Work towards a version 3 release.

### CODE REVIEW

**Comment by dblock** [comment]
Lets have @tombruijn party with this. You have r/w permissions to merge this @tombruijn, go ahead.

**Comment by dblock** [comment]
Also @tombruijn what's your rubygems email, for gem ownership.

**Comment by tombruijn** [comment]
@dblock Alright, I'll party with this :)
Will create some issues to discuss/plan/implement the topics I posted earlier (Rails 3, MongoMapper, jRuby, etc.).

my rubygems email is "tom@tomdebruijn.com"

**Comment by dblock** [comment]
Added @tombruijn to Rubygems.

**Pull request merged**
