### PR TITLE
Add mongoid-danger

### LINKED ISSUE #20: Add mongoid-danger
This means cleaning up CHANGELOG. See https://github.com/mongoid/mongoid-geospatial/pull/52 for an example.

### PR DESCRIPTION
**Pull request by tombruijn**
Closes #20

### CODE REVIEW

**Comment by dblock** [comment]
Thanks! Could you check the build? I think we need to lock down or remove some things under older rails's.

**Comment by dblock** [comment]
FYI, I've added DANGER_GITHUB_API_TOKEN to Travis.

**Comment by dblock** [comment]
Seems painful, but danger-changelog wants things in a certain format, ie. with the name of the person contributing. I've edited changelogs by hand many times :)

**Comment by tombruijn** [comment]
My first thought wasn't "painful", more like "silly".

But... what exactly does it want from me?

I've added names to the changes but still it doesn't like it? I can't reference PRs because there aren't PRs for most changes. What do I do?

**Comment by dblock** [comment]
It has a very particular format in mind that involves expanding the markdown link. The danger-changelog gem is just not smart enough to do references, so the names at the end of the change item need to include the link directly. I opened https://github.com/dblock/danger-changelog/issues/22 for adding support for that, if you feel like going down the rabbit hole :)

I fixed this PR up, it's ready to merge and is green. 

The good news is that it yells at developers for you, so once you can live with this format you never have to worry about it again :)

**Comment by tombruijn** [comment]
Ah I see.. I did try that format but it didn't remove the lines from the warnings. So after trying a couple variations I gave up 😞 

Thanks for the help! I will merge this now

**Pull request merged**
