### PR TITLE
Update for issue #42

### PR DESCRIPTION
**Pull request by streetlogics**
Fix for https://github.com/mongoid/mongo_session_store/issues/42

### CODE REVIEW

**Comment by streetlogics** [comment]
There was an alternative from rack that suggested doing this:
```
module Rack
  module Session
    class SessionId 
      def bson_type
        public_id.bson_type
      end

      def to_bson(arg1, arg2)
        public_id.to_bson(arg1, arg2)
      end
    end
  end
end
```

However, I'm not quite sure what I would consider the right place to put this code in the actual gem codebase itself or if it's worth just manually calling `.to_s` as this PR suggests

**Comment by tombruijn** [comment]
Hi @streetlogics,

Thanks for reporting the issue and creating a PR! That helps a lot :)
I myself haven't tested this on Rails 6 yet so that might be why the bug is in there. Looks like Rails 6 should be added to the build to see if there are any other problems as well.

I won't merge and publish this straight away though. I'll need to find some time to reproduce and debug the issue myself, just to make sure I understand it correctly. Does it happen on any Rails 6 app or should I account for anything else in a test app?
I will update here once I've gotten around to it.

**Comment by streetlogics** [comment]
Hey @tombruijn - in the ticket on mongoid’s jira tracker I have attached a .zip file of a demo rails project to recreate the issue.  Biggest thing I had to add was sidekick + devise to get the error to trigger when trying to view the sidekiq ui.  The ticket is here - https://jira.mongodb.org/browse/RUBY-2095

**Comment by tombruijn** [comment]
Fixed in PR #46, after reproducing a minimal setup with a small Rack app and adding a test setup for this issue. available in gem version 3.2.1 which I just published.

**Comment by tombruijn** [comment]
Thanks for reporting the issue @streetlogics !

**Pull request closed without merging**
